# Auto-generated by IdeaAI — gesture classifier for the IdeaBoard + IdeaSense Explorer.

from ideasense import IdeaSense
import time

# Inicializa la tarjeta IdeaSense para acceder a sensores y matriz LED
idea = IdeaSense()

# Cantidad de muestras que se tomarán para analizar el movimiento
WINDOW = 25

# Etiquetas de las clases que puede reconocer la red neuronal
LABELS = ["Calma", "Movimiento"]

# Iconos que se mostrarán en la matriz LED según la clasificación
ICONS = [
    [[0,1,0,1,0], [0,1,0,1,0], [0,0,0,0,0], [1,0,0,0,1], [0,1,1,1,0]],
    [[0,1,0,1,0], [0,1,0,1,0], [0,0,0,0,0], [0,1,1,1,0], [1,0,0,0,1]]
]  # 5x5 matrix icon per class

# Valores utilizados para normalizar las características de entrada
NORM_MEAN = [...]
NORM_STD = [...]

# Pesos de la primera capa de la red neuronal
W1 = [...]

# Sesgos (bias) de la primera capa
B1 = [...]

# Pesos de la capa de salida
W2 = [...]

# Sesgos de la capa de salida
B2 = [...]


def extract_features(window):
    """
    Extrae características estadísticas de una ventana de datos.
    Para cada eje del acelerómetro y giroscopio calcula:
    - Media
    - Desviación estándar
    - Valor mínimo
    - Valor máximo
    - Número de cruces (cambios significativos)
    """
    feats = []

    # Recorre los 6 ejes: AccX, AccY, AccZ, GyroX, GyroY, GyroZ
    for axis in range(6):

        # Inicialización de variables estadísticas
        s = 0.0
        mn = window[0][axis]
        mx = window[0][axis]

        # Obtiene suma, mínimo y máximo
        for r in window:
            v = r[axis]
            s += v
            if v < mn:
                mn = v
            if v > mx:
                mx = v

        # Calcula la media
        mean = s / len(window)

        # Calcula la desviación estándar
        var = 0.0
        for r in window:
            var += (r[axis] - mean) ** 2

        std = (var / len(window)) ** 0.5

        # Umbrales para detectar cambios de estado
        hi = mean + 0.3 * std
        lo = mean - 0.3 * std

        state = 0
        crossings = 0

        # Cuenta cuántas veces la señal cambia de un estado alto a bajo
        for r in window:
            v = r[axis]

            if v > hi:
                if state == -1:
                    crossings += 1
                state = 1

            elif v < lo:
                if state == 1:
                    crossings += 1
                state = -1

        # Guarda las 5 características calculadas
        feats.extend([mean, std, mn, mx, crossings])

    # Normaliza las características para que la red neuronal trabaje correctamente
    return [(feats[j] - NORM_MEAN[j]) / NORM_STD[j]
            for j in range(len(feats))]


def dense(inp, W, B, relu):
    """
    Implementa una capa densa (fully connected).
    Multiplica entradas por pesos y suma los sesgos.
    Opcionalmente aplica la función de activación ReLU.
    """
    out = []

    for j in range(len(B)):
        acc = B[j]

        for i in range(len(inp)):
            acc += inp[i] * W[i][j]

        # ReLU elimina valores negativos
        if relu and acc < 0:
            acc = 0.0

        out.append(acc)

    return out


def predict(window):
    """
    Realiza la clasificación usando la red neuronal.
    Retorna el índice de la clase con mayor puntuación.
    """

    # Obtiene características de la ventana de datos
    feats = extract_features(window)

    # Primera capa oculta
    h = dense(feats, W1, B1, True)

    # Capa de salida
    out = dense(h, W2, B2, False)

    # Busca la salida con mayor valor
    best = 0

    for i in range(1, len(out)):
        if out[i] > out[best]:
            best = i

    return best


def show_icon(pat):
    """
    Dibuja un icono 5x5 en la matriz LED.
    """
    for r in range(5):
        for c in range(5):
            idea.matrix[c, r] = pat[r][c]


# Bucle principal del programa
while True:

    # Almacena las muestras de sensores
    window = []

    # Captura WINDOW lecturas consecutivas
    for _ in range(WINDOW):

        # Lee acelerómetro
        a = idea.accel

        # Lee giroscopio
        g = idea.gyro

        # Guarda las 6 mediciones
        window.append(
            (a[0], a[1], a[2],
             g[0], g[1], g[2])
        )

        # Espera 40 ms entre lecturas
        time.sleep(0.04)

    # Clasifica la ventana de datos
    idx = predict(window)

    # Muestra el resultado por consola
    print(LABELS[idx])

    # Muestra el icono asociado a la clase detectada
    show_icon(ICONS[idx])
